const mongoose = require("mongoose");
const db = require("../models");

const dbcCardsSeed = [
    {
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Kevin",
        lastName: "Park",
        companyName: "Park",
        phoneNumber: "(555)505-5550",
        email: "www.parkseo.com",
        address: "77 Wellington Avenue",
        date: new Date(),
        img: "2.png",
    },{
        cardTags: "Architecture",
        firstName: "Ryan",
        lastName: "Morgan",
        companyName: "NLaurenarchitec",
        phoneNumber: "(514)451-4435)",
        email: "laurenm@gmail.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "3.png",
    },{
        cardTags: "Photography",
        firstName: "Farah",
        lastName: "Killian",
        companyName: "Farahphotography",
        phoneNumber: "(610)384-4827",
        email: "info@farahphotography.com",
        address: "957 Front St, Coatesville, PA 19320",
        date: new Date(),
        img: "4.png",
    },{
        cardTags: "Design",
        firstName: "Miria",
        lastName: "Perez",
        companyName: "Miria Floral",
        phoneNumber: "(414)342-0971)",
        email: "cmiriafloral@gmail.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "5.png",
    },{
        cardTags: "Journalism",
        firstName: "Helena",
        lastName: "Babbel",
        companyName: "HBabelscoops",
        phoneNumber: "(614)451-4422",
        email: "info@hbabel.com",
        address: "254 West Boulavard Berlin, Germany",
        date: new Date(),
        img: "6.png",
    },{
        cardTags: "Development",
        firstName: "Kim Lou",
        lastName: "Wan",
        companyName: "Create Developers",
        phoneNumber: "(987)4575-9567",
        email: "info@createdevelopers.com",
        address: "132 9th Street, Lakeview Lane, NY 87903",
        date: new Date(),
        img: "7.png",
    },{
        cardTags: "Marketing",
        firstName: "Mark",
        lastName: "Smith",
        companyName: "Brand Name",
        phoneNumber: "(123)456-7890",
        email: "marksmith@newbrandname.com",
        address: "123 Dummy, Lorem Ipsum",
        date: new Date(),
        img: "8.png",
    },{
        cardTags: "Engineering",
        firstName: "Mark",
        lastName: "Smith",
        companyName: "Marks company",
        phoneNumber: "(122)643-5534",
        email: "info@email.com",
        address: "155 44th Street, NY 11130",
        date: new Date(),
        img: "9.png",
    },{
        cardTags: "Web Development",
        firstName: "Narimi",
        lastName: "Miyauchi",
        companyName: "Nero",
        phoneNumber: "(509)560-1648",
        email: "narimi@nerostudio.com",
        address: "381 Mudlick Road",
        date: new Date(),
        img: "10.png",
    },{
        cardTags: "Videgraphy",
        firstName: "Mike",
        lastName: "Danielsen",
        companyName: "Danish Collective",
        phoneNumber: "(965)369-5502",
        email: "mike@danishcollective.com",
        address: "493 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "11.png",
    },{
        cardTags: "Real Estate",
        firstName: "Sofia",
        lastName: "Guillermo",
        companyName: "Revall",
        phoneNumber: "((485)9453-4395",
        email: "sofiag@revall.com",
        address: "8744 Main Street, Touscan, BC",
        date: new Date(),
        img: "12.png",
    },{
        cardTags: "Interior Design",
        firstName: "Sarah",
        lastName: "Maron",
        companyName: "Maron Designs",
        phoneNumber: "(112)1232 11",
        email: "sarah@marondesigns.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "13.png",
    },{
        cardTags: "Web design",
        firstName: "Jonathan",
        lastName: "Patterson",
        companyName: "Patterson Designs",
        phoneNumber: "(656)-8686-869",
        email: "jonathanpatt@design.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "14.png",
    },{
        cardTags: "Web Design",
        firstName: "Jacqueline",
        lastName: "Thompson",
        companyName: "Jacqueline Design",
        phoneNumber: "(656)-8686-869",
        email: "jacqline@jacquelinedesign.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "15.png",
    },{
        cardTags: "IT",
        firstName: "Mark",
        lastName: "Williams",
        companyName: "Bijou Tech SOlutions",
        phoneNumber: "(656)-8686-869",
        email: "mark@bijou.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "16.png",
    },{
        cardTags: "Web Design",
        firstName: "Rachel",
        lastName: "Beaudry",
        companyName: "Rachel Designs",
        phoneNumber: "(656)-8686-869",
        email: "rachel@racheldesigns.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "17.png",
    },{
        cardTags: "Web Design",
        firstName: "Simon",
        lastName: "Grayson",
        companyName: "Simon Grayson",
        phoneNumber: "(656)-8686-869",
        email: "simon@simondesigns.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "18.png",
    }
];