const mongoose = require("mongoose");
const db = require("../models");

const dbcCardsSeed = [
    {
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },{
        cardTags: "Engineering",
        firstName: "Clarie",
        lastName: "Mackintosh",
        companyName: "Novatech Technologies",
        phoneNumber: "(656)-8686-869",
        email: "clairem@novatechtechnologies.com",
        address: "425 Hidden Valley Road, NY 87903",
        date: new Date(),
        img: "1.png",
    },
];